version: '3'

services:

#
#  EVENTSTORE
#

  eventstore:
    image: eventstore/eventstore
    container_name: eventstore-node
    logging:
      driver: "none"
    ports:
      - "${EVENTSTORE_HTTP_CLIENT_PORT}:${ES_HTTP_PORT}"
      - "${EVENTSTORE_TCP_PORT}:${ES_TCP_PORT}"

#
# AGENDA
#

  agenda-inbox:
    container_name: agenda-inbox
    build: ./Inbox
    volumes:
      - "./Inbox:/app/src"
    ports:
      - "${AGENDA_INBOX_PORT}:${HOST_PORT}"
    depends_on:
      - eventstore
    env_file:
      - .env

  agenda-outbox:
    container_name: agenda-outbox
    build: ./Outbox
    volumes:
      - "./Outbox:/app/src"
    ports:
      - "${AGENDA_OUTBOX_PORT}:${HOST_PORT}"
    env_file:
      - .env

  agenda-querier-db:
    image: mongo
    container_name: agenda-querier-db
    logging:
      driver: "none"
    ports:
    - "${AGENDA_QUERIER_DB_PORT}:${DB_PORT}"
#    - "27017-27019:27017-27019"

  agenda-querier:
    container_name: agenda-querier
    build: ./Querier
    volumes:
      - "./Querier:/app/src"
    ports:
      - "${AGENDA_QUERIER_PORT}:${HOST_PORT}"
    depends_on:
      - eventstore
      - agenda-querier-db
